---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-referenced-internally
spec:
  steps:
    - name: task-remote
      image: gcr.io/distroless/python3:nonroot
      script: |
        #!/usr/bin/python3
        print("Hello Task Referenced Internally")
