---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-remote-annotations
spec:
  tasks:
    - name: task-spec
      taskSpec:
        steps:
          - name: task-spec
            image: registry.access.redhat.com/ubi8/ubi-micro:8.5
            script: |
              echo "Hello from taskSpec"
              exit 0

    - name: task-from-remote
      taskRef:
        name: task-remote

    - name: task-referenced-internally
      taskRef:
        name: task-referenced-internally
